name: CI

on:
  push:
    branches: ["**"]
    paths:
      - "client/**"
      - "server/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/**"
  pull_request:
    branches: ["**"]
    paths:
      - "client/**"
      - "server/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/**"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  client:
    name: Client - Lint & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies (root workspace)
        run: npm ci

      - name: Lint (client)
        run: npm --workspace client run lint

      - name: Build (client)
        run: npm --workspace client run build

  server:
    name: Server - Type Check & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies (root workspace)
        run: npm ci

      - name: Build (server)
        run: npm --workspace server run build
